Alarm broadcast notif
MarinaRomanova/65 pull request #5
Opened 2021-11-01 17:54 UTC by MarinaRomanova

## Handle Birthday reminders
- Alarm is set for the birthday inside a DetailFragment to send a pending intent to a Broadcast Receiver `ReminderReceiver`
- `ReminderReceiver` sets up and sends a local Notification.

### Remarks (todo)
- Leap year is not managed
- A picker could be used to set preferences for notifications time. Currently alarm's setup time is used.
- Test new functionalities
- Nicer design

<img src="https://user-images.githubusercontent.com/36896406/139711782-be91ed46-0b82-4599-b738-af17b4244a9a.png" width="250" /> <img src="https://user-images.githubusercontent.com/36896406/139711784-019020d5-021c-4bd1-9148-cb5a43960518.png" width="250" /> <img src="https://user-images.githubusercontent.com/36896406/139711785-bdc70e5c-8eca-4db5-a6f0-08f27ac5c91d.png" width="250" />

2021-11-02 05:16 UTC, goblinr requested changes
Нужно еще обработать ситуацию с високосным годом.

2021-11-02 05:16 UTC, goblinr commented on app/src/main/java/com/marina/romanova/assignment/detail/ReminderReceiver.kt
> +const val REMINDER_ACTION = "com.marina.romanova.assignment.detail.REMINDER_ACTION"
можно сделать  `private`

2021-11-02 05:16 UTC, goblinr commented on app/src/main/java/com/marina/romanova/assignment/detail/DetailFragment.kt
> +    private val alarmManager by lazy { app.getSystemService(Context.ALARM_SERVICE) as AlarmManager }
1. `as` -> `as?` иначе может быть крэш, если не будет найден системный сервис `AlarmManager`
2. `lazy` по умолчанию имеет потокобезопасную реализацию. В конкретно этом случае, нам не нужна потокобезопасность, т.к. этот код всегда вызывается из main  потока

2021-11-02 05:16 UTC, goblinr commented on app/src/main/java/com/marina/romanova/assignment/detail/ReminderReceiver.kt
> +        val notificationManager = ContextCompat.getSystemService(context, NotificationManager::class.java) as NotificationManager
`as` -> `as?`  иначе возможен крэш

2021-11-02 13:16 UTC, MarinaRomanova commented on app/src/main/java/com/marina/romanova/assignment/MainActivity.kt
> +                navigateToList(shouldLoad = true)
Done

2021-11-02 13:17 UTC, MarinaRomanova commented on app/src/main/java/com/marina/romanova/assignment/common/DateExtensions.kt
> +    val dateFormatter =  SimpleDateFormat(formatIn, locale )
Done

2021-11-02 13:17 UTC, MarinaRomanova commented on app/src/main/java/com/marina/romanova/assignment/common/NotificationUtils.kt
> +    val builder = NotificationCompat.Builder(context.applicationContext, CHANNEL_ID )
Done

2021-11-02 13:17 UTC, MarinaRomanova commented on app/src/main/java/com/marina/romanova/assignment/detail/ReminderReceiver.kt
> +const val REMINDER_ACTION = "com.marina.romanova.assignment.detail.REMINDER_ACTION"
Done

2021-11-02 13:17 UTC, MarinaRomanova commented on app/src/main/java/com/marina/romanova/assignment/detail/DetailFragment.kt
> +    private val alarmManager by lazy { app.getSystemService(Context.ALARM_SERVICE) as AlarmManager }
Done

2021-11-02 13:17 UTC, MarinaRomanova commented on app/src/main/java/com/marina/romanova/assignment/detail/ReminderReceiver.kt
> +        val notificationManager = ContextCompat.getSystemService(context, NotificationManager::class.java) as NotificationManager
Done

2021-11-02 17:26 UTC, goblinr requested changes

2021-11-02 17:26 UTC, goblinr commented on app/src/main/java/com/marina/romanova/assignment/detail/DetailFragment.kt
> +        if (date.isLeapYear) {
А почему мы сдвигаем год до високосного для всех у кого было ДР в високосный год? Нас же интересуют только ребята, которые родились 29 февраля. Только для них нужно сдвигать до високосного года.

2021-11-02 17:26 UTC, goblinr commented on app/src/main/java/com/marina/romanova/assignment/detail/DetailFragment.kt
> +            nextBD.plusYears(1)
Опять же, для всех кто родился не 29 февраля, мы должны сдвигать на 1 год. А вот для тех кто родился 29 февраля - до следующего високосного года.

2021-11-02 17:26 UTC, goblinr commented on app/src/main/java/com/marina/romanova/assignment/detail/ReminderReceiver.kt
> +            LocalDate.now().plusYears(1).atStartOfDay(ZoneOffset.UTC).toInstant().toEpochMilli(),
И здесь, то же необходимо учитывать ребят, которые родились в високосный год 29 февраля

2021-11-02 23:21 UTC, MarinaRomanova commented on app/src/main/java/com/marina/romanova/assignment/detail/DetailFragment.kt
> +        if (date.isLeapYear) {
Поправлено

2021-11-02 23:21 UTC, MarinaRomanova commented on app/src/main/java/com/marina/romanova/assignment/detail/DetailFragment.kt
> +            nextBD.plusYears(1)
Поправлено

2021-11-02 23:22 UTC, MarinaRomanova commented on app/src/main/java/com/marina/romanova/assignment/detail/ReminderReceiver.kt
> +            LocalDate.now().plusYears(1).atStartOfDay(ZoneOffset.UTC).toInstant().toEpochMilli(),
Поправлено

2021-11-05 09:14 UTC, goblinr requested changes

2021-11-05 09:14 UTC, goblinr commented on app/src/main/java/com/marina/romanova/assignment/detail/DetailFragment.kt
> +            nextBD = nextBD.plusYears(if (nextBD.isLeapYear) 4 else  1)
Прибавлять 4 года мы должны только если ДР у контакта - 29 февраля.

2021-11-05 11:31 UTC, MarinaRomanova commented on app/src/main/java/com/marina/romanova/assignment/detail/DetailFragment.kt
> +            nextBD = nextBD.plusYears(if (nextBD.isLeapYear) 4 else  1)
ну теперь вроде как done 🙈

2021-11-06 16:20 UTC, goblinr approved these changes

2021-11-06 16:21 UTC, merged